# Generated by Django 6.0.5 on 2026-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_communemedia_is_hero_alter_association_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communeinfo',
            name='region',
            field=models.CharField(default='Centre-Val de Loire', max_length=100, verbose_name='Région'),
        ),
    ]
