# Generated by Django 6.0.5 on 2026-05-31 17:56

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pharmacy_senior_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('places_disponibles', models.PositiveSmallIntegerField(default=0, verbose_name='Places disponibles')),
                ('infos', models.TextField(blank=True, verbose_name='Informations')),
            ],
            options={
                'verbose_name': 'Assistante maternelle',
                'verbose_name_plural': 'Assistantes maternelles',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='GlassCollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(blank=True, help_text='Ex: Parking de la Mairie, Rue de la Forêt…', max_length=255, verbose_name='Nom / libellé')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description / précisions')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Point de collecte du verre',
                'verbose_name_plural': 'Points de collecte du verre',
                'ordering': ['order', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LeisureCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('horaires', models.TextField(blank=True, verbose_name='Horaires / informations')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Centre de loisirs',
                'verbose_name_plural': 'Centres de loisirs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mediatheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(default='Médiathèque de Dhuizon', max_length=255, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('horaires', models.TextField(blank=True, verbose_name="Horaires d'ouverture")),
                ('infos', models.TextField(blank=True, verbose_name='Informations complémentaires')),
            ],
            options={
                'verbose_name': 'Médiathèque',
                'verbose_name_plural': 'Médiathèques',
            },
        ),
        migrations.CreateModel(
            name='MunicipalCouncilor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(blank=True, help_text='Ex: Maire, Adjoint au maire, Conseiller municipal…', max_length=150, verbose_name='Rôle / fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/conseillers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Photo')),
                ('is_conseil_jeunes', models.BooleanField(default=False, help_text='Cocher si ce conseiller fait partie du conseil des jeunes.', verbose_name='Conseil des jeunes')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Conseiller municipal',
                'verbose_name_plural': 'Conseillers municipaux',
                'ordering': ['order', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='NextCouncilMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.DateField(verbose_name='Date du prochain conseil')),
                ('heure', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('lieu', models.CharField(blank=True, default='Salle du conseil municipal', max_length=255, verbose_name='Lieu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Prochain conseil municipal',
                'verbose_name_plural': 'Prochain conseil municipal',
            },
        ),
        migrations.CreateModel(
            name='TextileCollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom / libellé')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description / précisions')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Point de collecte de textiles',
                'verbose_name_plural': 'Points de collecte de textiles',
                'ordering': ['order', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_transport', models.CharField(choices=[('scolaire', 'Transport scolaire'), ('regulier', 'Transport régulier')], max_length=20, verbose_name='Type')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom / numéro de ligne')),
                ('description', models.TextField(blank=True, help_text='Trajet, arrêts, fréquence…', verbose_name='Description')),
                ('horaires', models.TextField(blank=True, verbose_name='Horaires')),
                ('lien', models.URLField(blank=True, help_text="Lien vers le site de l'opérateur ou les horaires en ligne.", verbose_name='Lien')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['type_transport', 'order', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='healthcareprofessional',
            options={'ordering': ['profession', 'nom', 'prenom'], 'verbose_name': 'Professionnel de santé', 'verbose_name_plural': 'Professionnels de santé'},
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='adresse',
            field=models.CharField(blank=True, help_text='Utile pour les praticiens hors maison de santé (ex: dentistes).', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='infos_complementaires',
            field=models.TextField(blank=True, help_text="Horaires personnalisés, secteur conventionnel, informations d'accès…", verbose_name='Informations complémentaires'),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/associations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='communemedia',
            name='image',
            field=models.ImageField(upload_to='images/galerie/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='municipalcouncilreport',
            name='pdf',
            field=models.FileField(upload_to='documents/conseils/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/actualites/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='url',
            field=models.CharField(blank=True, help_text='Lien de destination du raccourci (ex: /ecole/ ou https://…)', max_length=255, validators=[core.validators.validate_safe_link_url], verbose_name='Lien (URL ou chemin)'),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='seniorresidence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Image'),
        ),
    ]
