# Generated by Django 6.0.5 on 2026-06-03 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nursery_lien_alter_quicklink_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/creches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Logo de la crèche'),
        ),
    ]
