# Generated by Django 6.0.5 on 2026-06-04 13:00

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_nursery_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabaneCocou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la cabane')),
                ('description', models.TextField(verbose_name='Description')),
                ('statut', models.CharField(choices=[('en_projet', '🔜 En projet'), ('en_construction', '🚧 En construction'), ('ouvert', '✅ Ouvert')], default='en_projet', max_length=20, verbose_name='Statut')),
                ('capacite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacité (personnes)')),
                ('tarif', models.CharField(blank=True, help_text='Ex : À partir de 120€/nuit', max_length=150, verbose_name='Tarif indicatif')),
                ('lien', models.URLField(blank=True, validators=[core.validators.validate_safe_link_url], verbose_name='Lien de réservation / site')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/tourisme/cabanes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Cabane Coocou',
                'verbose_name_plural': 'Cabanes Coocou',
                'ordering': ['order', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CommerceProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_activite', models.CharField(max_length=255, verbose_name="Nom de l'activité")),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('personnel', models.CharField(blank=True, help_text='Nom(s) du ou des responsables / gérants.', max_length=255, verbose_name='Personnel / Responsable')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Commerce / Professionnel',
                'verbose_name_plural': 'Commerces & Professionnels',
                'ordering': ['order', 'nom_activite'],
            },
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'hébergement")),
                ('type_hebergement', models.CharField(choices=[('auberge', 'Auberge'), ('hotel', 'Hôtel'), ('gite', 'Gîte'), ('camping', 'Camping'), ('autre', 'Autre')], default='auberge', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('site_web', models.URLField(blank=True, validators=[core.validators.validate_safe_link_url], verbose_name='Site web')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/tourisme/hebergements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Hébergement',
                'verbose_name_plural': 'Hébergements',
                'ordering': ['order', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LieuTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('temps_trajet', models.CharField(blank=True, help_text='Ex : 15 min en voiture, 30 min à vélo…', max_length=100, verbose_name='Temps de trajet')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Distance (km)')),
                ('lien', models.URLField(blank=True, validators=[core.validators.validate_safe_link_url], verbose_name='Lien vers le site officiel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/tourisme/lieux/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Lieu touristique',
                'verbose_name_plural': 'Lieux touristiques',
                'ordering': ['order', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='communemedia',
            name='is_hero_tourisme',
            field=models.BooleanField(default=False, help_text='Cocher pour utiliser cette photo comme fond de la page Tourisme.', verbose_name='Image héro (fond tourisme)'),
        ),
    ]
