# Generated by Django 6.0.5 on 2026-06-04 14:49

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Génère les slugs pour les associations existantes."""
    Association = apps.get_model('core', 'Association')
    for asso in Association.objects.all():
        if not asso.slug:
            base_slug = slugify(asso.nom)
            slug = base_slug
            n = 1
            while Association.objects.filter(slug=slug).exclude(pk=asso.pk).exists():
                slug = f"{base_slug}-{n}"
                n += 1
            asso.slug = slug
            asso.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_patrimoine_item'),
    ]

    operations = [
        # 1 — Ajouter le champ sans contrainte unique pour permettre la migration des données
        migrations.AddField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Généré automatiquement depuis le nom.', max_length=270, verbose_name='Slug (URL)'),
            preserve_default=False,
        ),
        # 2 — Peupler les slugs sur les enregistrements existants
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
        # 3 — Ajouter la contrainte unique maintenant que les slugs sont remplis
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, help_text='Généré automatiquement depuis le nom.', max_length=270, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='icon',
            field=models.CharField(choices=[('school', '🎓'), ('sports_soccer', '⚽'), ('local_pharmacy', '💊'), ('home', '🏠'), ('info', 'ℹ️'), ('restaurant', '🍽️'), ('room_service', '🛎️'), ('kebab_dining', '🍢'), ('local_pizza', '🍕'), ('partly_cloudy_day', '⛅'), ('sunny', '☀️'), ('cloud', '☁️'), ('rainy_snow', '🌧️'), ('thunderstorm', '⛈️'), ('rainy', '🌧️'), ('health_and_safety', '🩺'), ('health_cross', '➕'), ('location_on', '📍'), ('phone', '☎️'), ('email', '✉️'), ('people', '👥'), ('event', '📅'), ('library_books', '📚'), ('elderly_woman', '👵'), ('child_care', '👶'), ('recycling', '♻️'), ('delete', '🗑️'), ('medical_services', '🏥'), ('directions_car', '🚌'), ('shopping_cart', '🛒'), ('park', '🌳'), ('directions', '🗺️'), ('account_balance', '🏛️'), ('newspaper', '📰'), ('calendar_month', '📅'), ('mail', '📧'), ('alarm', '🕒'), ('pin_drop', '📍'), ('book_ribbon', '📚'), ('celebration', '🎉'), ('construction', '🏗️'), ('home_repair_service', '🔨'), ('forest', '🌲'), ('compost', '♻️'), ('how_to_vote', '🗳️'), ('diversity_3', '👥'), ('trophy', '🏆'), ('comedy_mask', '🎭'), ('festival', '🎪'), ('shield', '🛡️'), ('badge', '👮'), ('local_fire_department', '🔥'), ('map', '🗺️'), ('church', '⛪'), ('file_export', '📄'), ('assignment', '📋'), ('photo', '🖼️'), ('send', '📨'), ('accessibility', '♿')], help_text='Sélectionnez une icône prédéfinie', max_length=50, verbose_name='Icône'),
        ),
    ]
