# Generated by Django 4.2 on 2026-07-30 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_periscolaireinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periscolaireinfo',
            name='reglement_cantine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/periscolaire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Règlement de la cantine (PDF)'),
        ),
        migrations.AddField(
            model_name='periscolaireinfo',
            name='reglement_garderie_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/periscolaire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Règlement de la garderie (PDF)'),
        ),
    ]
