# Generated by Django 6.0.5 on 2026-08-02 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_periscolaireinfo_reglement_cantine_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communeinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affiché dans le header du site et sur les formulaires. Laissez vide pour utiliser le logo par défaut.', null=True, upload_to='images/commune/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Logo de la commune'),
        ),
    ]
