# Generated by Django 6.1.1 on 2026-09-16 12:39

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_menucantine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucantine',
            options={'ordering': ['-annee', '-numero_semaine'], 'verbose_name': 'Menu de la cantine', 'verbose_name_plural': 'Menus de la cantine'},
        ),
        migrations.AlterUniqueTogether(
            name='menucantine',
            unique_together={('annee', 'numero_semaine')},
        ),
        migrations.AddField(
            model_name='leisurecenter',
            name='menu_pdf',
            field=models.FileField(blank=True, help_text='Un seul PDF contenant le menu pour le centre de loisirs.', null=True, upload_to='documents/centre_loisirs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Menu (PDF)'),
        ),
        migrations.AddField(
            model_name='menucantine',
            name='pdf',
            field=models.FileField(blank=True, help_text='Un seul PDF par semaine.', null=True, upload_to='documents/cantine/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Fichier PDF du menu'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='assurance_scolaire',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name='Assurance extra-scolaire'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='jugement_familial',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name='Jugement familial'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='justificatif_quotient_familial',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name='Justificatif quotient familial'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='livret_famille_doc',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name='Livret de famille (Document)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='personnes_habilitees_identite',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name="Pièce d'identité (Personnes habilitées)"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='vaccins',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name='Vaccins'),
        ),
        migrations.AlterField(
            model_name='menucantine',
            name='annee',
            field=models.IntegerField(default=core.models.current_year, help_text='Exemple : 2024', verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='menucantine',
            name='numero_semaine',
            field=models.IntegerField(default=core.models.current_week, help_text='Exemple : 34', verbose_name='Numéro de la semaine'),
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='accompagnement',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='entree',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='laitage',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='note',
        ),
        migrations.RemoveField(
            model_name='menucantine',
            name='plat_principal',
        ),
    ]
