# Generated by Django 6.1.1 on 2026-09-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_menucantine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncentreloisirs',
            name='docs_source',
            field=models.ForeignKey(blank=True, help_text="Si la famille n'a pas fourni de nouveaux fichiers, pointe vers l'inscription précédente qui possède les documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_utilisant_ces_docs', to='core.inscriptioncentreloisirs', verbose_name="Documents repris depuis l'inscription"),
        ),
    ]
