# Generated by Django 6.0.5 on 2026-09-22 14:23

import core.models
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_docs_source_to_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defibrillateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(help_text='Ex: Mairie, Salle des fêtes, École...', max_length=255, verbose_name='Nom / lieu')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude GPS')),
                ('description', models.TextField(blank=True, help_text='Accès, disponibilité 24h/24, étage...', verbose_name='Informations complémentaires')),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher si le défibrillateur est hors service.', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Défibrillateur (DAE)',
                'verbose_name_plural': 'Défibrillateurs (DAE)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('voirie', 'Voirie / Route'), ('eclairage', 'Éclairage public'), ('dechets', 'Déchets / Propreté'), ('espaces_verts', 'Espaces verts'), ('batiment', 'Bâtiment communal'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS')),
                ('adresse_approximative', models.CharField(blank=True, help_text="Fournie par l'habitant ou calculée depuis les coordonnées GPS.", max_length=255, verbose_name='Adresse approximative')),
                ('statut', models.CharField(choices=[('nouveau', '🆕 Nouveau'), ('en_cours', '🔄 En cours de traitement'), ('resolu', '✅ Résolu'), ('rejete', '❌ Rejeté')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('email_signalant', models.EmailField(blank=True, help_text="Pour pouvoir notifier l'habitant du traitement de son signalement.", max_length=254, verbose_name='Email du signalant (optionnel)')),
                ('commentaire_mairie', models.TextField(blank=True, verbose_name='Commentaire interne mairie')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='adminallowedip',
            options={'ordering': ['label', 'ip_address'], 'verbose_name': 'IP autorisÃ©e (/admin/)', 'verbose_name_plural': 'IP autorisÃ©es (/admin/)'},
        ),
        migrations.AlterModelOptions(
            name='demarcheadministrative',
            options={'ordering': ['ordre', 'titre'], 'verbose_name': 'DÃ©marche administrative', 'verbose_name_plural': 'DÃ©marches administratives'},
        ),
        migrations.AlterModelOptions(
            name='gite',
            options={'ordering': ['order', 'nom'], 'verbose_name': 'GÃ®te', 'verbose_name_plural': 'GÃ®tes'},
        ),
        migrations.AlterModelOptions(
            name='healthcareprofessional',
            options={'ordering': ['order', 'profession', 'nom', 'prenom'], 'verbose_name': 'Professionnel de santÃ©', 'verbose_name_plural': 'Professionnels de santÃ©'},
        ),
        migrations.AlterModelOptions(
            name='healthcenter',
            options={'ordering': ['nom'], 'verbose_name': 'Maison de santÃ©', 'verbose_name_plural': 'Maisons de santÃ©'},
        ),
        migrations.AlterModelOptions(
            name='hebergement',
            options={'ordering': ['order', 'nom'], 'verbose_name': 'HÃ©bergement', 'verbose_name_plural': 'HÃ©bergements'},
        ),
        migrations.AlterModelOptions(
            name='histoiredhuizon',
            options={'ordering': ['order', 'date_label'], 'verbose_name': 'Ã\x89vÃ©nement historique', 'verbose_name_plural': 'Ã\x89vÃ©nements historiques'},
        ),
        migrations.AlterModelOptions(
            name='mediatheque',
            options={'verbose_name': 'MÃ©diathÃ¨que', 'verbose_name_plural': 'MÃ©diathÃ¨que'},
        ),
        migrations.AlterModelOptions(
            name='mediathequeschedule',
            options={'ordering': ['jour_index', 'heure_ouverture'], 'verbose_name': 'Horaire mÃ©diathÃ¨que', 'verbose_name_plural': 'Horaires mÃ©diathÃ¨que'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['event_date'], 'verbose_name': 'ActualitÃ©', 'verbose_name_plural': 'ActualitÃ©s'},
        ),
        migrations.AlterModelOptions(
            name='nursery',
            options={'ordering': ['nom'], 'verbose_name': 'CrÃ¨che', 'verbose_name_plural': 'CrÃ¨ches'},
        ),
        migrations.AlterModelOptions(
            name='patrimoineitem',
            options={'ordering': ['order', 'nom'], 'verbose_name': 'Ã\x89lÃ©ment de patrimoine', 'verbose_name_plural': 'Ã\x89lÃ©ments de patrimoine'},
        ),
        migrations.AlterModelOptions(
            name='periscolaireinfo',
            options={'verbose_name': 'Information PÃ©riscolaire', 'verbose_name_plural': 'Informations PÃ©riscolaires'},
        ),
        migrations.AlterModelOptions(
            name='randonnee',
            options={'ordering': ['order', 'nom'], 'verbose_name': 'RandonnÃ©e', 'verbose_name_plural': 'RandonnÃ©es'},
        ),
        migrations.AlterModelOptions(
            name='recyclingcenter',
            options={'ordering': ['nom'], 'verbose_name': 'DÃ©chetterie', 'verbose_name_plural': 'DÃ©chetteries'},
        ),
        migrations.AlterModelOptions(
            name='recyclingcenterschedule',
            options={'ordering': ['centre', 'saison', 'jour_index'], 'verbose_name': 'Horaire de dÃ©chetterie', 'verbose_name_plural': 'Horaires de dÃ©chetterie'},
        ),
        migrations.AlterModelOptions(
            name='reservationcentreloisirs',
            options={'ordering': ['-date'], 'verbose_name': 'RÃ©servation centre de loisirs', 'verbose_name_plural': 'RÃ©servations centre de loisirs'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['nom'], 'verbose_name': 'Ã\x89cole', 'verbose_name_plural': 'Ã\x89coles'},
        ),
        migrations.AlterModelOptions(
            name='seniorresidence',
            options={'ordering': ['nom'], 'verbose_name': 'RÃ©sidence senior', 'verbose_name_plural': 'RÃ©sidences seniors'},
        ),
        migrations.AlterModelOptions(
            name='seniorresidenceschedule',
            options={'ordering': ['jour_index', 'heure_ouverture'], 'verbose_name': 'Horaire rÃ©sidence seniors', 'verbose_name_plural': 'Horaires rÃ©sidence seniors'},
        ),
        migrations.AlterModelOptions(
            name='sportfacility',
            options={'ordering': ['type_equipement', 'nom'], 'verbose_name': 'Ã\x89quipement sportif', 'verbose_name_plural': 'Ã\x89quipements sportifs'},
        ),
        migrations.AlterModelOptions(
            name='sportfacilitytype',
            options={'ordering': ['nom'], 'verbose_name': "Type d'Ã©quipement sportif", 'verbose_name_plural': "Types d'Ã©quipements sportifs"},
        ),
        migrations.AlterModelOptions(
            name='wastecollectionschedule',
            options={'ordering': ['jour_index', 'type_dechet'], 'verbose_name': 'Planning de collecte des dÃ©chets', 'verbose_name_plural': 'Plannings de collecte des dÃ©chets'},
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='can_access_centre_loisirs',
            field=models.BooleanField(default=False, help_text="En plus de l'accÃ¨s au panel gÃ©nÃ©ral, cet admin peut aussi accÃ©der au centre de loisirs.", verbose_name='AccÃ¨s Centre de Loisirs'),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='is_centre_loisirs',
            field=models.BooleanField(default=False, help_text="AccÃ¨s restreint au panneau de gestion du centre de loisirs (pas d'accÃ¨s au panel gÃ©nÃ©ral).", verbose_name='Est Admin Centre de Loisirs uniquement'),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text="Les Super Admins peuvent crÃ©er et gÃ©rer d'autres administrateurs.", verbose_name='Est Super Admin (Mairie)'),
        ),
        migrations.AlterField(
            model_name='adminallowedip',
            name='label',
            field=models.CharField(help_text='Ex. : Mairie de Dhuizon, Bureau du maireâ\x80¦', max_length=120, verbose_name='LibellÃ©'),
        ),
        migrations.AlterField(
            model_name='agencepostale',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='agencepostaleschedule',
            name='ferme',
            field=models.BooleanField(default=False, verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, help_text='GÃ©nÃ©rÃ© automatiquement depuis le nom.', max_length=270, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='association',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('cree', 'CrÃ©Ã©'), ('modifie', 'ModifiÃ©'), ('supprime', 'SupprimÃ©')], max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.TextField(blank=True, help_text='JSON : champs modifiÃ©s avec valeurs avant / aprÃ¨s', verbose_name='DÃ©tail des modifications'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(help_text='Nom du modÃ¨le Django (ex : HealthcareProfessional)', max_length=100, verbose_name='ModÃ¨le concernÃ©'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(help_text="Valeur __str__ de l'objet au moment de l'action", max_length=500, verbose_name="ReprÃ©sentation de l'objet"),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='section_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='LibellÃ© de la section'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='section_slug',
            field=models.CharField(help_text='Slug de la section concernÃ©e (ex : sante-professionnels)', max_length=100, verbose_name='Section du panneau'),
        ),
        migrations.AlterField(
            model_name='cabanecocou',
            name='capacite',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CapacitÃ© (personnes)'),
        ),
        migrations.AlterField(
            model_name='cabanecocou',
            name='lien',
            field=models.URLField(blank=True, validators=[core.validators.validate_safe_link_url], verbose_name='Lien de rÃ©servation / site'),
        ),
        migrations.AlterField(
            model_name='cabanecocou',
            name='statut',
            field=models.CharField(choices=[('en_projet', 'ð\x9f\x94\x9c En projet'), ('en_construction', 'ð\x9f\x9a§ En construction'), ('ouvert', 'â\x9c\x85 Ouvert')], default='en_projet', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cabanecocou',
            name='tarif',
            field=models.CharField(blank=True, help_text='Ex : Ã\x80 partir de 120â\x82¬/nuit', max_length=150, verbose_name='Tarif indicatif'),
        ),
        migrations.AlterField(
            model_name='childcareprofessional',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='PrÃ©nom'),
        ),
        migrations.AlterField(
            model_name='childcareprofessional',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='nom_activite',
            field=models.CharField(max_length=255, verbose_name="Nom de l'activitÃ©"),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='personnel',
            field=models.CharField(blank=True, help_text='Nom(s) du ou des responsables / gÃ©rants.', max_length=255, verbose_name='Personnel / Responsable'),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='commerceschedule',
            name='ferme',
            field=models.BooleanField(default=False, help_text='Cocher si le commerce est fermÃ© ce jour-lÃ\xa0.', verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='commerceschedule',
            name='heure_fermeture',
            field=models.TimeField(blank=True, help_text='Laisser vide si fermÃ© toute la journÃ©e.', null=True, verbose_name='Heure de fermeture'),
        ),
        migrations.AlterField(
            model_name='commerceschedule',
            name='heure_ouverture',
            field=models.TimeField(blank=True, help_text='Laisser vide si fermÃ© toute la journÃ©e.', null=True, verbose_name="Heure d'ouverture"),
        ),
        migrations.AlterField(
            model_name='communeinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affichÃ© dans le header du site et sur les formulaires. Laissez vide pour utiliser le logo par dÃ©faut.', null=True, upload_to='images/commune/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Logo de la commune'),
        ),
        migrations.AlterField(
            model_name='communeinfo',
            name='presentation',
            field=models.TextField(verbose_name='Texte de prÃ©sentation de la commune'),
        ),
        migrations.AlterField(
            model_name='communeinfo',
            name='region',
            field=models.CharField(default='Centre-Val de Loire', max_length=100, verbose_name='RÃ©gion'),
        ),
        migrations.AlterField(
            model_name='communeinfo',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone de la mairie'),
        ),
        migrations.AlterField(
            model_name='communeinfoschedule',
            name='ferme',
            field=models.BooleanField(default=False, verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='communemedia',
            name='description',
            field=models.TextField(blank=True, help_text='Optionnel â\x80\x93 description dÃ©taillÃ©e de la photo.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communemedia',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Cocher pour utiliser cette photo comme fond de la section principale.', verbose_name='Image hÃ©ro (fond accueil)'),
        ),
        migrations.AlterField(
            model_name='communemedia',
            name='is_hero_tourisme',
            field=models.BooleanField(default=False, help_text='Cocher pour utiliser cette photo comme fond de la page Tourisme.', verbose_name='Image hÃ©ro (fond tourisme)'),
        ),
        migrations.AlterField(
            model_name='communemedia',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre / lÃ©gende'),
        ),
        migrations.AlterField(
            model_name='demarcheadministrative',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='demarches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='Fichier PDF Ã\xa0 tÃ©lÃ©charger (ex: CERFA)'),
        ),
        migrations.AlterField(
            model_name='demarcheadministrative',
            name='icone',
            field=models.CharField(default='article', help_text="Ex: 'description', 'favorite', 'home'", max_length=50, verbose_name='IcÃ´ne Google Material'),
        ),
        migrations.AlterField(
            model_name='demarcheadministrative',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre de la dÃ©marche'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_activite',
            field=models.CharField(max_length=255, verbose_name="Nom de l'activitÃ©"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='personnel',
            field=models.CharField(blank=True, help_text='Nom(s) du ou des responsables / gÃ©rants.', max_length=255, verbose_name='Personnel / Responsable'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='entrepriseschedule',
            name='ferme',
            field=models.BooleanField(default=False, help_text="Cocher si l'entreprise est fermÃ©e ce jour-lÃ\xa0.", verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='entrepriseschedule',
            name='heure_fermeture',
            field=models.TimeField(blank=True, help_text='Laisser vide si fermÃ© toute la journÃ©e.', null=True, verbose_name='Heure de fermeture'),
        ),
        migrations.AlterField(
            model_name='entrepriseschedule',
            name='heure_ouverture',
            field=models.TimeField(blank=True, help_text='Laisser vide si fermÃ© toute la journÃ©e.', null=True, verbose_name="Heure d'ouverture"),
        ),
        migrations.AlterField(
            model_name='gite',
            name='capacite',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CapacitÃ© (personnes)'),
        ),
        migrations.AlterField(
            model_name='gite',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du gÃ®te'),
        ),
        migrations.AlterField(
            model_name='gite',
            name='tarif',
            field=models.CharField(blank=True, help_text='Ex : Ã\x80 partir de 80 â\x82¬ / nuit', max_length=100, verbose_name='Tarif indicatif'),
        ),
        migrations.AlterField(
            model_name='gite',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='glasscollectionpoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / prÃ©cisions'),
        ),
        migrations.AlterField(
            model_name='glasscollectionpoint',
            name='nom',
            field=models.CharField(blank=True, help_text='Ex: Parking de la Mairie, Rue de la ForÃªtâ\x80¦', max_length=255, verbose_name='Nom / libellÃ©'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='adresse',
            field=models.CharField(blank=True, help_text='Utile pour les praticiens hors maison de santÃ© (ex: dentistes).', max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionnels', to='core.healthcenter', verbose_name='Maison de santÃ©'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='infos_complementaires',
            field=models.TextField(blank=True, help_text="Horaires personnalisÃ©s, secteur conventionnel, informations d'accÃ¨sâ\x80¦", verbose_name='Informations complÃ©mentaires'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Les professionnels sont triÃ©s par ordre croissant, puis par profession et nom.', verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='PrÃ©nom'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='profession',
            field=models.CharField(help_text='Exemple : MÃ©decin gÃ©nÃ©raliste, KinÃ©sithÃ©rapeuteâ\x80¦', max_length=150, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'hÃ©bergement"),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='type_hebergement',
            field=models.CharField(choices=[('auberge', 'Auberge'), ('hotel', 'HÃ´tel'), ('gite', 'GÃ®te'), ('camping', 'Camping'), ('autre', 'Autre')], default='auberge', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='histoiredhuizon',
            name='date_label',
            field=models.CharField(help_text="Texte affichÃ© comme repÃ¨re temporel (ex: 1000, XIXe siÃ¨cle, Aujourd'huiâ\x80¦)", max_length=100, verbose_name='Date / pÃ©riode'),
        ),
        migrations.AlterField(
            model_name='histoiredhuizon',
            name='evenement',
            field=models.TextField(help_text="Description de l'Ã©vÃ©nement historique.", verbose_name='Ã\x89vÃ©nement'),
        ),
        migrations.AlterField(
            model_name='histoiredhuizon',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Les Ã©vÃ©nements sont affichÃ©s par ordre croissant.', verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='docs_source',
            field=models.ForeignKey(blank=True, help_text="Si la famille n'a pas fourni de nouveaux fichiers, pointe vers l'inscription prÃ©cÃ©dente qui possÃ¨de les documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_utilisant_ces_docs', to='core.inscriptioncentreloisirs', verbose_name="Documents repris depuis l'inscription"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='pai_sante',
            field=models.TextField(blank=True, verbose_name='PAI informations de santÃ© (lunettes, fauteuil, etc.)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='personnes_habilitees_identite',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.'), core.validators.validate_inscription_document_size], verbose_name="PiÃ¨ce d'identitÃ© (Personnes habilitÃ©es)"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='personnes_habilitees_texte',
            field=models.TextField(blank=True, verbose_name="Personnes habilitÃ©es Ã\xa0 venir chercher l'enfant"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='prenom_enfant',
            field=models.CharField(max_length=100, verbose_name="PrÃ©nom de l'enfant"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='prenom_responsable_1',
            field=models.CharField(max_length=100, verbose_name='PrÃ©nom (Responsable 1)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='prenom_responsable_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='PrÃ©nom (Responsable 2)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='telephone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone (Responsable 1)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone (Responsable 2)'),
        ),
        migrations.AlterField(
            model_name='leisurecenter',
            name='capacite_max',
            field=models.PositiveIntegerField(default=30, help_text="Nombre maximum d'enfants pouvant Ãªtre accueillis par jour.", verbose_name='CapacitÃ© journaliÃ¨re maximale'),
        ),
        migrations.AlterField(
            model_name='leisurecenter',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='leisuredaystatus',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'FermÃ©'), ('ferie', 'FÃ©riÃ©')], default='ouvert', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='lieutouristique',
            name='temps_trajet',
            field=models.CharField(blank=True, help_text='Ex : 15 min en voiture, 30 min Ã\xa0 vÃ©loâ\x80¦', max_length=100, verbose_name='Temps de trajet'),
        ),
        migrations.AlterField(
            model_name='mediatheque',
            name='infos',
            field=models.TextField(blank=True, verbose_name='Informations complÃ©mentaires'),
        ),
        migrations.AlterField(
            model_name='mediatheque',
            name='nom',
            field=models.CharField(default='MÃ©diathÃ¨que de Dhuizon', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='mediatheque',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='mediathequeschedule',
            name='ferme',
            field=models.BooleanField(default=False, verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='mediathequeschedule',
            name='mediatheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_planning', to='core.mediatheque', verbose_name='MÃ©diathÃ¨que'),
        ),
        migrations.AlterField(
            model_name='menucantine',
            name='annee',
            field=models.IntegerField(default=core.models.current_year, help_text='Exemple : 2024', verbose_name='AnnÃ©e'),
        ),
        migrations.AlterField(
            model_name='menucantine',
            name='numero_semaine',
            field=models.IntegerField(default=core.models.current_week, help_text='Exemple : 34', verbose_name='NumÃ©ro de la semaine'),
        ),
        migrations.AlterField(
            model_name='municipalcouncilor',
            name='comissions',
            field=models.CharField(blank=True, help_text='Ex: Urbanisme, Environnement, Cultureâ\x80¦', max_length=255, verbose_name='Commissions'),
        ),
        migrations.AlterField(
            model_name='municipalcouncilor',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='PrÃ©nom'),
        ),
        migrations.AlterField(
            model_name='municipalcouncilor',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Maire, Adjoint au maire, Conseiller municipalâ\x80¦', max_length=150, verbose_name='RÃ´le / fonction'),
        ),
        migrations.AlterField(
            model_name='municipalcouncilreport',
            name='description',
            field=models.TextField(blank=True, help_text='Optionnel â\x80\x93 rÃ©sumÃ© du conseil.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, help_text="Optionnel â\x80\x93 nom de l'auteur de l'article.", max_length=150, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='news',
            name='event_date',
            field=models.DateField(help_text="Date Ã\xa0 laquelle l'Ã©vÃ©nement se dÃ©roule.", verbose_name="Date de l'Ã©vÃ©nement"),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='PubliÃ©'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(help_text='RÃ©sumÃ© affichÃ© sur la liste des actualitÃ©s.', max_length=500, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text='GÃ©nÃ©rÃ© automatiquement depuis le titre.', max_length=270, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='lien',
            field=models.URLField(blank=True, help_text='Lien vers le site de la crÃ¨che ou de la gestionnaire.', validators=[core.validators.validate_safe_link_url], verbose_name='Lien vers le site de la crÃ¨che'),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/creches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Logo de la crÃ¨che'),
        ),
        migrations.AlterField(
            model_name='nursery',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=500, verbose_name='Page visitÃ©e'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='ClÃ© de session'),
        ),
        migrations.AlterField(
            model_name='patrimoineitem',
            name='description',
            field=models.TextField(blank=True, help_text='Texte affichÃ© sous le nom du lieu.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='patrimoineitem',
            name='nom',
            field=models.CharField(help_text='Ex: Mairie, Ã\x89glise Saint-Pierre, Ã\x89tangsâ\x80¦', max_length=200, verbose_name='Nom du lieu'),
        ),
        migrations.AlterField(
            model_name='patrimoineitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Les Ã©lÃ©ments sont affichÃ©s par ordre croissant.', verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='periscolaireinfo',
            name='presentation',
            field=models.TextField(blank=True, help_text="Ce texte s'affichera au-dessus du formulaire d'inscription.", verbose_name='Texte de prÃ©sentation'),
        ),
        migrations.AlterField(
            model_name='periscolaireinfo',
            name='reglement_cantine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/periscolaire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='RÃ¨glement de la cantine (PDF)'),
        ),
        migrations.AlterField(
            model_name='periscolaireinfo',
            name='reglement_garderie_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/periscolaire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Seuls les fichiers PDF sont autorisés.')], verbose_name='RÃ¨glement de la garderie (PDF)'),
        ),
        migrations.AlterField(
            model_name='periscolaireinfo',
            name='titre',
            field=models.CharField(default='Inscription aux services pÃ©riscolaires', max_length=255, verbose_name='Titre de la section'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='horaires',
            field=models.TextField(blank=True, help_text='Ex. : garde de nuit, fermetures exceptionnellesâ\x80¦ Les horaires pour le statut Â« ouvert / fermÃ© Â» se gÃ¨rent ci-dessous.', verbose_name='Informations complÃ©mentaires'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='pharmacyschedule',
            name='ferme',
            field=models.BooleanField(default=False, verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='icon',
            field=models.CharField(choices=[('school', 'ð\x9f\x8e\x93'), ('sports_soccer', 'â\x9a½'), ('local_pharmacy', 'ð\x9f\x92\x8a'), ('home', 'ð\x9f\x8f\xa0'), ('info', 'â\x84¹ï¸\x8f'), ('restaurant', 'ð\x9f\x8d½ï¸\x8f'), ('room_service', 'ð\x9f\x9b\x8eï¸\x8f'), ('kebab_dining', 'ð\x9f\x8d¢'), ('local_pizza', 'ð\x9f\x8d\x95'), ('partly_cloudy_day', 'â\x9b\x85'), ('sunny', 'â\x98\x80ï¸\x8f'), ('cloud', 'â\x98\x81ï¸\x8f'), ('rainy_snow', 'ð\x9f\x8c§ï¸\x8f'), ('thunderstorm', 'â\x9b\x88ï¸\x8f'), ('rainy', 'ð\x9f\x8c§ï¸\x8f'), ('health_and_safety', 'ð\x9f©º'), ('health_cross', 'â\x9e\x95'), ('location_on', 'ð\x9f\x93\x8d'), ('phone', 'â\x98\x8eï¸\x8f'), ('email', 'â\x9c\x89ï¸\x8f'), ('people', 'ð\x9f\x91¥'), ('event', 'ð\x9f\x93\x85'), ('library_books', 'ð\x9f\x93\x9a'), ('elderly_woman', 'ð\x9f\x91µ'), ('child_care', 'ð\x9f\x91¶'), ('recycling', 'â\x99»ï¸\x8f'), ('delete', 'ð\x9f\x97\x91ï¸\x8f'), ('medical_services', 'ð\x9f\x8f¥'), ('directions_car', 'ð\x9f\x9a\x8c'), ('shopping_cart', 'ð\x9f\x9b\x92'), ('park', 'ð\x9f\x8c³'), ('directions', 'ð\x9f\x97ºï¸\x8f'), ('account_balance', 'ð\x9f\x8f\x9bï¸\x8f'), ('newspaper', 'ð\x9f\x93°'), ('calendar_month', 'ð\x9f\x93\x85'), ('mail', 'ð\x9f\x93§'), ('alarm', 'ð\x9f\x95\x92'), ('pin_drop', 'ð\x9f\x93\x8d'), ('book_ribbon', 'ð\x9f\x93\x9a'), ('celebration', 'ð\x9f\x8e\x89'), ('construction', 'ð\x9f\x8f\x97ï¸\x8f'), ('home_repair_service', 'ð\x9f\x94¨'), ('forest', 'ð\x9f\x8c²'), ('compost', 'â\x99»ï¸\x8f'), ('how_to_vote', 'ð\x9f\x97³ï¸\x8f'), ('diversity_3', 'ð\x9f\x91¥'), ('trophy', 'ð\x9f\x8f\x86'), ('comedy_mask', 'ð\x9f\x8e\xad'), ('festival', 'ð\x9f\x8eª'), ('shield', 'ð\x9f\x9b¡ï¸\x8f'), ('badge', 'ð\x9f\x91®'), ('local_fire_department', 'ð\x9f\x94¥'), ('map', 'ð\x9f\x97ºï¸\x8f'), ('church', 'â\x9bª'), ('file_export', 'ð\x9f\x93\x84'), ('assignment', 'ð\x9f\x93\x8b'), ('photo', 'ð\x9f\x96¼ï¸\x8f'), ('send', 'ð\x9f\x93¨'), ('accessibility', 'â\x99¿')], help_text='SÃ©lectionnez une icÃ´ne prÃ©dÃ©finie', max_length=50, verbose_name='IcÃ´ne'),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='label',
            field=models.CharField(help_text="Texte affichÃ© sous l'icÃ´ne (ex: Ã\x89cole, Sportâ\x80¦)", max_length=100, verbose_name='LibellÃ©'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='adresse_depart',
            field=models.CharField(blank=True, help_text='Adresse ou point de repÃ¨re.', max_length=255, null=True, verbose_name='Lieu de dÃ©part'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='carte_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/randonnees/cartes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Image de la carte du tracÃ©'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='description_courte',
            field=models.CharField(help_text='AffichÃ©e sur la carte dans la liste des loisirs.', max_length=500, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='description_detaillee',
            field=models.TextField(help_text='AffichÃ©e sur la page dÃ©diÃ©e Ã\xa0 la randonnÃ©e.', verbose_name='Description dÃ©taillÃ©e'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='images/randonnees/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format image non autorisé. Utilisez : JPG, PNG, WEBP ou GIF.')], verbose_name='Image de prÃ©sentation'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='niveau_difficulte',
            field=models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='facile', max_length=20, verbose_name='Niveau de difficultÃ©'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la randonnÃ©e'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='slug',
            field=models.SlugField(blank=True, help_text='GÃ©nÃ©rÃ© automatiquement si laissÃ© vide.', max_length=255, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='randonnee',
            name='temps_parcours',
            field=models.CharField(help_text='Ex: 2h30', max_length=100, verbose_name='Temps de parcours estimÃ©'),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='recyclingcenterschedule',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.recyclingcenter', verbose_name='DÃ©chetterie'),
        ),
        migrations.AlterField(
            model_name='recyclingcenterschedule',
            name='ferme',
            field=models.BooleanField(default=False, help_text='Cocher si la dÃ©chetterie est fermÃ©e ce jour-lÃ\xa0 pour cette saison.', verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='recyclingcenterschedule',
            name='saison',
            field=models.CharField(choices=[('ete', 'Ã\x89tÃ© (01/04 â\x86\x92 31/10)'), ('hiver', 'Hiver (01/11 â\x86\x92 31/03)')], max_length=10, verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='reservationcentreloisirs',
            name='date',
            field=models.DateField(verbose_name='Date rÃ©servÃ©e'),
        ),
        migrations.AlterField(
            model_name='reservationcentreloisirs',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'ValidÃ©e'), ('refusee', 'RefusÃ©e'), ('annulee', 'AnnulÃ©e')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nb_eleves',
            field=models.PositiveIntegerField(verbose_name="Nombre d'Ã©lÃ¨ves"),
        ),
        migrations.AlterField(
            model_name='school',
            name='nb_inscrits_rentree',
            field=models.PositiveIntegerField(verbose_name='Inscrits Ã\xa0 la derniÃ¨re rentrÃ©e'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'Ã©cole"),
        ),
        migrations.AlterField(
            model_name='school',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='seniorresidence',
            name='horaires',
            field=models.TextField(blank=True, help_text="PrÃ©cisions d'accueil. Les horaires pour le statut Â« ouvert / fermÃ© Â» se gÃ¨rent ci-dessous.", verbose_name='Informations complÃ©mentaires'),
        ),
        migrations.AlterField(
            model_name='seniorresidence',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='seniorresidenceschedule',
            name='ferme',
            field=models.BooleanField(default=False, verbose_name='FermÃ© ce jour'),
        ),
        migrations.AlterField(
            model_name='seniorresidenceschedule',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_planning', to='core.seniorresidence', verbose_name='RÃ©sidence'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'Ã©quipement"),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='type_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='core.sportfacilitytype', verbose_name="Type d'Ã©quipement"),
        ),
        migrations.AlterField(
            model_name='sportfacilitytype',
            name='icone',
            field=models.CharField(blank=True, help_text="Optionnel â\x80\x93 ex: 'fas fa-futbol' ou 'â\x9a½'", max_length=50, verbose_name='IcÃ´ne (classe CSS ou emoji)'),
        ),
        migrations.AlterField(
            model_name='sportfacilitytype',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name="Type d'Ã©quipement"),
        ),
        migrations.AlterField(
            model_name='textilecollectionpoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / prÃ©cisions'),
        ),
        migrations.AlterField(
            model_name='textilecollectionpoint',
            name='nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom / libellÃ©'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True, help_text='Trajet, arrÃªts, frÃ©quenceâ\x80¦', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='lien',
            field=models.URLField(blank=True, help_text="Lien vers le site de l'opÃ©rateur ou les horaires en ligne.", verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom / numÃ©ro de ligne'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_transport',
            field=models.CharField(choices=[('scolaire', 'Transport scolaire'), ('regulier', 'Transport rÃ©gulier')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='wastecollectionschedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / prÃ©cisions'),
        ),
        migrations.AlterField(
            model_name='wastecollectionschedule',
            name='type_dechet',
            field=models.CharField(choices=[('menagers', 'DÃ©chets mÃ©nagers'), ('recyclables', 'Recyclables (tri sÃ©lectif)'), ('verre', 'Verre'), ('encombrants', 'Encombrants'), ('vegetaux', 'DÃ©chets verts / vÃ©gÃ©taux'), ('autre', 'Autre')], max_length=20, verbose_name='Type de dÃ©chet'),
        ),
        migrations.CreateModel(
            name='SignalementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='signalements/', verbose_name='Photo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.signalement', verbose_name='Signalement')),
            ],
            options={
                'verbose_name': 'Photo de signalement',
                'verbose_name_plural': 'Photos de signalement',
                'ordering': ['order'],
            },
        ),
    ]
