# Generated by Django 6.1.1 on 2026-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_defibrillateur_signalement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien (optionnel)')),
                ('date_programmee', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure d'envoi programmée")),
                ('est_envoye', models.BooleanField(default=False, verbose_name='Déjà envoyé ?')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi réel")),
            ],
            options={
                'verbose_name': 'Notification Mobile',
                'verbose_name_plural': 'Notifications Mobiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
