SETTINGS_MENU = [
    ('Contenu du site', [
        ('Actualités', 'Ajouter, modifier ou supprimer des actualités', '📰', 'panel_crud_list', {'app_label': 'core', 'model_name': 'news'}),
        ('Informations commune', 'Population, adresse, horaires, présentation.', '🏛️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'communeinfo'}),
        ('Horaires Mairie', 'Gérer les horaires d\'ouverture de la mairie', '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'communeinfoschedule'}),
        ('Galerie & photo principale', "Photos du site et image de fond de l'accueil", '🖼️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'communemedia'}),
        ('Histoire de Dhuizon', 'Frise chronologique de la page Découvrir', '📜', 'panel_crud_list', {'app_label': 'core', 'model_name': 'histoiredhuizon'}),
        ('Patrimoine & lieux remarquables', 'Lieux affichés sur la page Découvrir Dhuizon', '🏰', 'panel_crud_list', {'app_label': 'core', 'model_name': 'patrimoineitem'}),
        ('Liens rapides', "Boutons d'accès rapide sur la page d'accueil", '⚡', 'panel_crud_list', {'app_label': 'core', 'model_name': 'quicklink'}),
    ]),
    ('Vie pratique', [
        ('École', "Informations sur l'école de la commune", '🎓', 'panel_crud_list', {'app_label': 'core', 'model_name': 'school'}),
        ('Inscription périscolaire', 'Informations et formulaire', '🎒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'periscolaireinfo'}),
        ('Centre de santé', 'Centre médical et professionnels de santé', '🏥', 'panel_crud_list', {'app_label': 'core', 'model_name': 'healthcenter'}),
        ('Pharmacie', 'Coordonnées de la pharmacie locale', '💊', 'panel_crud_list', {'app_label': 'core', 'model_name': 'pharmacy'}),
        ('Résidence seniors', 'Foyer et services pour les aînés', '👵', 'panel_crud_list', {'app_label': 'core', 'model_name': 'seniorresidence'}),
        ('Crèche', 'Informations sur la crèche municipale', '👶', 'panel_crud_list', {'app_label': 'core', 'model_name': 'nursery'}),
        ('Assistantes maternelles', 'Liste des assistantes maternelles agrées', '🧸', 'panel_crud_list', {'app_label': 'core', 'model_name': 'childcareprofessional'}),
        ('Médiathèque', 'Horaires et contacts de la médiathèque', '📚', 'panel_crud_list', {'app_label': 'core', 'model_name': 'mediatheque'}),
        ('Horaires Médiathèque', 'Gérer les horaires d\'ouverture de la médiathèque', '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'mediathequeschedule'}),
        ('Transports', 'Transports scolaires et réguliers', '🚌', 'panel_crud_list', {'app_label': 'core', 'model_name': 'transport'}),
        ('Collecte des déchets', 'Jours et horaires de passage des poubelles', '🗑️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'wastecollectionschedule'}),
        ('Points de collecte du verre', 'Adresses des conteneurs verre', '♻️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'glasscollectionpoint'}),
        ('Points de collecte de textiles', 'Adresses des bâches textiles', '👕', 'panel_crud_list', {'app_label': 'core', 'model_name': 'textilecollectionpoint'}),
        ('Déchèterie', "Adresse et horaires d'ouverture", '🏭', 'panel_crud_list', {'app_label': 'core', 'model_name': 'recyclingcenter'}),
        ('Horaires Déchetterie', 'Gérer les horaires été / hiver de la déchetterie', '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'recyclingcenterschedule'}),
        ('Agence postale', "Coordonnées et horaires de l'agence postale", '✉️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'agencepostale'}),
        ('Horaires Agence postale', 'Gérer les horaires d\'ouverture de l\'agence postale', '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'agencepostaleschedule'}),
    ]),
    ('Loisirs', [
        ('Équipements sportifs', 'Terrains, salles et installations sportives', '⚽', 'panel_crud_list', {'app_label': 'core', 'model_name': 'sportfacility'}),
        ('Types d\'équipements sportifs', 'Catégories d\'équipements sportifs', '🏟️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'sportfacilitytype'}),
        ('Centre de loisirs', 'Centre de loisirs municipal', '🎨', 'panel_crud_list', {'app_label': 'core', 'model_name': 'leisurecenter'}),
        ('Centre de loisirs - Réservations', 'Gérer les inscriptions et les réservations', '📅', 'admin_cl_dashboard', {}),
        ('Chemins de randonnée', 'Parcours et sentiers locaux', '🥾', 'panel_crud_list', {'app_label': 'core', 'model_name': 'randonnee'}),
    ]),
    ('Autres contenus', [
        ('Conseil municipal', 'Comptes-rendus et documents du conseil', '🏛️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'municipalcouncilreport'}),
        ('Prochain conseil municipal', 'Date du prochain conseil municipal', '📅', 'panel_crud_list', {'app_label': 'core', 'model_name': 'nextcouncilmeeting'}),
        ('Conseillers municipaux', 'Liste des élus et conseil des jeunes', '👥', 'panel_crud_list', {'app_label': 'core', 'model_name': 'municipalcouncilor'}),
        ('Associations', 'Associations locales et leurs coordonnées', '🤝', 'panel_crud_list', {'app_label': 'core', 'model_name': 'association'}),
        ('Démarches administratives', 'État civil, élections, livrets de famille.', '📝', 'panel_crud_list', {'app_label': 'core', 'model_name': 'demarcheadministrative'}),
    ]),
    ('Tourisme', [
        ('Lieux à visiter', 'Chambord, Cheverny et autres sites à visiter', '📸', 'panel_crud_list', {'app_label': 'core', 'model_name': 'lieutouristique'}),
        ('Cabanes Coocou', 'Hébergements insolites en forêt solognote', '🏕️', 'panel_crud_list', {'app_label': 'core', 'model_name': 'cabanecocou'}),
        ('Hébergements', 'Auberges, hôtels, gîtes et hébergements', '🏨', 'panel_crud_list', {'app_label': 'core', 'model_name': 'hebergement'}),
        ('Gîtes', 'Gîtes touristiques de la commune', '🏡', 'panel_crud_list', {'app_label': 'core', 'model_name': 'gite'}),
    ]),
    ('Commerces & Professionnels', [
        ('Commerces', "Annuaire des commerces et professionnels de la commune", '🏪', 'panel_crud_list', {'app_label': 'core', 'model_name': 'commerce'}),
        ('Horaires des commerces', "Horaires d'ouverture par commerce et par jour", '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'commerceschedule'}),
        ('Entreprises', "Annuaire des entreprises implantées sur la commune", '🏢', 'panel_crud_list', {'app_label': 'core', 'model_name': 'entreprise'}),
        ('Horaires des entreprises', "Horaires d'ouverture par entreprise et par jour", '🕒', 'panel_crud_list', {'app_label': 'core', 'model_name': 'entrepriseschedule'}),
    ]),
    ('Sécurité & Logs & Comptes', [
        (
            'Historique des modifications',
            "Consultez l'historique des actions (qui a modifié quoi) sur les 3 derniers mois.",
            '🕵️',
            'admin_audit_logs',
            {},
        ),
        (
            'IP autorisées (/admin/)',
            "Adresses IP de la mairie autorisées sur l'interface Django /admin/",
            '🔒',
            'panel_crud_list',
            {'app_label': 'core', 'model_name': 'adminallowedip'},
        ),
        (
            'Comptes administrateurs',
            "Créer ou supprimer les comptes des employés de la mairie (Super Admin uniquement).",
            '👮🏻',
            'panel_crud_list',
            {'app_label': 'core', 'model_name': 'adminaccount', 'super_admin_only': True},
        ),
    ]),
]
