# Generated by Django 4.2 on 2026-07-29 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_inscriptioncentreloisirs_assurance_scolaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriscolaireInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(default='Inscription aux services périscolaires', max_length=255, verbose_name='Titre de la section')),
                ('presentation', models.TextField(blank=True, help_text="Ce texte s'affichera au-dessus du formulaire d'inscription.", verbose_name='Texte de présentation')),
            ],
            options={
                'verbose_name': 'Information Périscolaire',
                'verbose_name_plural': 'Informations Périscolaires',
            },
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='assurance_scolaire',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name='Assurance extra-scolaire'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='jugement_familial',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name='Jugement familial'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='justificatif_quotient_familial',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name='Justificatif quotient familial'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='livret_famille_doc',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name='Livret de famille (Document)'),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='personnes_habilitees_identite',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name="Pièce d'identité (Personnes habilitées)"),
        ),
        migrations.AlterField(
            model_name='inscriptioncentreloisirs',
            name='vaccins',
            field=models.FileField(blank=True, null=True, upload_to='inscriptions_cl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif'], message='Format non autorisé. Utilisez : PDF, JPG, PNG ou WEBP.')], verbose_name='Vaccins'),
        ),
    ]
