# Generated by Django 4.2 on 2026-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_communeinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='can_access_centre_loisirs',
            field=models.BooleanField(default=False, help_text="En plus de l'accès au panel général, cet admin peut aussi accéder au centre de loisirs.", verbose_name='Accès Centre de Loisirs'),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='is_centre_loisirs',
            field=models.BooleanField(default=False, help_text="Accès restreint au panneau de gestion du centre de loisirs (pas d'accès au panel général).", verbose_name='Est Admin Centre de Loisirs uniquement'),
        ),
    ]
